# Generated by Django 3.1.3 on 2022-11-15 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성날짜'),
            preserve_default=False,
        ),
    ]
