# Generated by Django 4.1.3 on 2022-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='a_de',
            field=models.IntegerField(default=0, verbose_name='검출한 수'),
        ),
        migrations.AddField(
            model_name='admin',
            name='a_wh',
            field=models.IntegerField(default=0, verbose_name='보류한 수'),
        ),
    ]
