# Generated by Django 3.1.3 on 2022-11-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plate', '0002_car_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_image',
            field=models.ImageField(default=1, unique=True, upload_to='images/'),
            preserve_default=False,
        ),
    ]
